disabled_rules:
excluded:
    - Pods/Alamofire
    - Pods/AlamofireImage
line_length: 200
type_body_length:
    - 300 # warning
    - 400 # error
function_body_length:
    - 100 # warning
    - 400 # error
type_name:
    excluded:
        - Tv
        - AKTrakt_iOSTests
variable_name:
    excluded:
        - id
        - URLString
        - URLRequest
