language: objective-c
osx_image: xcode7.3 
xcode_workspace: AKTrakt.xcworkspace
xcode_scheme: tvOS
before_install:
  - gem update cocoapods
  - pod repo update
script:
  - xcodebuild test -workspace AKTrakt.xcworkspace -scheme Tests -destination 'name=iPhone 6s'
  - xctool -workspace AKTrakt.xcworkspace -scheme tvOS build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - xctool -workspace AKTrakt.xcworkspace -scheme iOS build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
